
---
title: "Time Series Forecast -  Spark"
output:
  html_document:
    toc: true
---


```{r}
%md
# Time Series Forecasting - Spark
This script runs time series models for variables into the future for each Product ID using Gapply and Spark UDF
```


```{r}
install.packages("SparkR")
library(data.table)
library(mlflow)
library(tidyverse)
install_mlflow()
```


```{r}
library(SparkR)
```


```{r}
### Start ML Flow & Track
# Set Up ML Flow 
experiment_location  =  "/Archive/TEST_MLFLOW"
RunTimeStamp <- Sys.time()
mlflow_set_experiment(experiment_location)
run <- mlflow_start_run()

print(experiment_location)
print(RunTimeStamp)
print(run$run_id)
```


```{r}
library(SparkR)
mrd <-  SparkR::as.DataFrame(read.csv("/dbfs/FileStore/tables/time_series_Forecast_Spark_-54bd9.csv",header=TRUE))
planrangeDAT <- read.csv("/dbfs/FileStore/tables/PlanningRange.csv",header=TRUE)
display(head(mrd))
```


```{r}
#Determine forecast period
planrangeDAT$PlanningRangeStartDate  = as.Date.factor(planrangeDAT$PlanningRangeStartDate)
planrangeDAT$PlanningRangeEndDate =  as.Date.factor(planrangeDAT$PlanningRangeEndDate)
nAhead <- (planrangeDAT$PlanningNumberOfWeeks)
display(planrangeDAT)
```


```{r}
runTSModels <- function (key, x) 
{
    require("forecast")
    require("lubridate")
    x <- x[!is.na(x$DATE), ]
    x <- x[order(x$DATE), ]
    if (timeType == "week") {
        tsFreq = 52
        minWeek <- week(min(x$DATE))
        minYear <- year(min(x$DATE))
        maxWeek <- week(max(x$DATE))
        maxYear <- year(max(x$DATE))
        maxMonth <- month(max(x$DATE))
        RDATE <- as.data.frame(seq.Date(from = planrangeDAT$PlanningRangeStartDate, 
            by = "week", length.out = nAhead))
    }
    forecasts = lapply(X = 1:length(varsToPredict), function(i) {
        thisVar <- varsToPredict[i]
        tsDat <- x[, get("thisVar")]
        myts <- ts(tsDat, start = c(minYear, minWeek), end = c(maxYear, 
            maxWeek), frequency = tsFreq)
        if ("arima" %in% algos) {
            fit <- auto.arima(myts)
            AR_fitStat <- as.data.frame(summary(fit))$RMSE
            forecastPreds <- forecast(fit, h = nAhead)
            AR_forecast <- as.data.frame(forecastPreds)
            names(AR_forecast) <- c("pred", "lo80", "hi80", "lo95", 
                "high95")
        }
        if ("rw" %in% algos) {
            fit <- rwf(myts, h = nAhead, drift = TRUE)
            RW_fitStat <- as.data.frame(summary(fit))$RMSE
            RW_forecast <- as.data.frame(fit)
            names(RW_forecast) <- c("pred", "lo80", "hi80", "lo95", 
                "high95")
        }
        if ("naive" %in% algos) {
            fit <- snaive(myts)
            forecastPreds <- forecast(fit, h = nAhead)
            Naive_fitStat <- as.data.frame(summary(fit))$RMSE
            Naive_forecast <- as.data.frame(forecastPreds)
            names(Naive_forecast) <- c("pred", "lo80", "hi80", 
                "lo95", "high95")
        }
        bestModel <- cbind(AR_fitStat, RW_fitStat, Naive_fitStat)
        inds = which(bestModel == min(bestModel), arr.ind = TRUE)
        selectedMod = colnames(bestModel)[inds[, 2]]
        selectedMod
        if (selectedMod == "AR_fitStat") {
            y <- as.data.frame(cbind(key, RDATE, AR_forecast$pred))
            y$selectedMod <- "ARIMA"
        }
        else if (selectedMod == "RW_fitStat") {
            y <- as.data.frame(cbind(key, RDATE, RW_forecast$pred))
            y$selectedMod <- "RW"
        }
        else if (selectedMod == "Naive_fitStat") {
            y <- as.data.frame(cbind(key, RDATE, Naive_forecast$pred))
            y$selectedMod <- "NAIVE"
        }
        names(y) <- c("Product_ID", "DATE", "PRED", "selectedMod")
        y$Variable <- thisVar
        return(y)
    })
    forecastsOut <- do.call(rbind, forecasts)
    forecastsOut
}
```


```{r}
%md

##### TS Modelling and Forecast (Product_ID level) Using Gapply #####

```


```{r}
#Run TS algorithms
algos <- c("arima", "rw", "naive")
varsToPredict <- names(mrd)[grepl(pattern="V",x=names(mrd),fixed=TRUE)]
timeType <- "week"

schema <- structType(structField("Product_ID", "string"),
                     structField("DATE", "date"),
                     structField("PRED", "double"),
                     structField("selectedMod", "string"),
                     structField("Variable", "string"))

xVarsPreds <- gapply(mrd, mrd$"Product_ID", runTSModels, schema)
xVarsPreds
```


```{r}
display(xVarsPreds)
```


```{r}
dbfsPath  = "dbfs:/mnt/adls/Test/Databricks/"
if (length(varsToPredict) > 0){
path = paste0(dbfsPath,"forecastvars/")
SparkR::write.df(xVarsPreds,source = "delta", path = path, mode = "overwrite", partitionBy = "Product_ID")
}
```


```{r}
# Create row and append to tracker table
print(Sys.time()-RunTimeStamp)
runTable <- data.table(timeStamp = RunTimeStamp, runID = run$run_id, uri=mlflow_get_tracking_uri(), experiment_location=experiment_location, experiment_id=run$experiment_id,stage= "Test TS Forecasting Script")
display(runTable)
mlflow_end_run()
```

